version: '3.1'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: data_test
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456789
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql
  web:
    image: product-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/data_test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
volumes:
  db_data: {}