
server:
  port: 9091

spring:
  application:
    name: gateway-service

  cloud:
    gateway: #Phần cài đặt chính của Spring Cloud Gateway, cung cấp các cấu hình để định tuyến các yêu cầu tới các service khác
      discovery:
        locator:
          enabled: true # Tự động phát hiện và đăng ký các service được quản lý bởi Consul để định tuyến
      routes:
        - id: account-service
          uri: lb://account-service # URL đích mà Gateway sẽ chuyển tiếp yêu cầu. Sử dụng lb (load balance - Cân bằng tải)
          # định tuyến tới service account-service
          predicates:
            - Path=/account/** # Điều kiện áp dụng cho route. Trong trường hợp này, yêu cầu bất kì đường dẫn bắt đầu bằng /account
          filters: # Bộ lọc xử lý hoặc biến đổi yêu cầu trước khi chuyển tiếp.
            - RewritePath=/account/(?<path>.*), /$\{path} # Loại bỏ phần /account/ khỏi url trước khi đến service account-service

        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - RewritePath=/customer/(?<path>.*), /$\{path}

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - RewritePath=/order/(?<path>.*), /$\{path}

        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product/**
          filters:
#            - RemoveRequestHeader=Authorization
            - RewritePath=/product/(?<path>.*), /$\{path}

    consul: # Cấu hình để kết nối với Consul cho việc phát hiện và quản lý service
      host: localhost
      port: 8500

  main:
    web-application-type: reactive # Thiết lập ứng dụng theo dạng reactive(phản ứng), tức là sử dụng Spring WebFlux thay vì Spring MVC truyền thống
    allow-bean-definition-overriding: true # Cho phép định nghĩa nhiều bean có cùng tên, và bean định nghĩa sau sẽ bị đè lên các định nghĩa trước

  config:
    import: optional:consul:localhost:8500 # Chỉ định Spring sử dụng Consul để nhập các cấu hình tùy chọn từ localhost:8500,
    # điều này giúp Spring ứng dụng có thể tải các cấu hình từ Consul
