
server:
  port: 8083

spring:
  application:
    name: order-service
  cloud:
    consul:
      host: localhost
      port: 8500
  config:
    import: optional:consul:localhost:8500

#---
#spring:
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone1
#  config:
#    activate:
#      on-profile: zone1
#---
#spring:
#  cloud:
#    consul:
#      discovery:
#        instanceZone: zone2
#  config:
#    activate:
#      on-profile: zone2
#
#logging:
#  level:
#    com:
#      example:
#        orderservice: DEBUG